jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
        brew update-reset /usr/local/Homebrew
        ln -s "$PWD" "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-formula-analytics"
        brew style homebrew/formula-analytics
        brew formula-analytics --setup
      displayName: Tests

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew
        sudo mkdir -p /home/linuxbrew
        sudo git clone https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
        sudo mkdir -p "$HOMEBREW_REPOSITORY/Library/Taps/homebrew"
        sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-formula-analytics"
        sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
        "$HOMEBREW_REPOSITORY/bin/brew" style homebrew/formula-analytics
        "$HOMEBREW_REPOSITORY/bin/brew" formula-analytics --setup
      displayName: Tests
