name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:
    paths: '*'
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Install Homebrew on Linux
      run: |
        HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew
        sudo mkdir -p /home/linuxbrew
        sudo git clone https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
        sudo mkdir -p "$HOMEBREW_REPOSITORY/Library/Taps/homebrew"
        sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-formula-analytics"
        sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
      if: matrix.os == 'ubuntu-latest'

    - name: Set up Homebrew
      run: |
        brew update-reset /usr/local/Homebrew
        ln -s "$PWD" "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-formula-analytics"
      if: matrix.os == 'macOS-latest'

    - name: Run brew style
      run: |
        export PATH="/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:$PATH"
        brew style homebrew/formula-analytics

    - name: Test formula-analytics setup
      run: |
        export PATH="/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:$PATH"
        brew formula-analytics --setup
